### ISSUE TITLE
use isort pre-commit (https://github.com/timothycrosley/isort) as a sorting tool of imports

### ISSUE THREAD

**Issue by zhukovgreen** [oamg/leapp-repository#564]
# Blocked by #562 (line length)

Under the scope:
- [ ] setup isort pre-commit hook  (https://github.com/timothycrosley/isort) with the following configuration

in pyproject.toml
```toml
[tool.isort]
line_length = {project-accepted-line-length}
use_parentheses = true
balanced_wrapping = true
include_trailing_comma = true
multi_line_output = 3
known_third_party=["pytest", "distro", "pyudev", "mock"]
```
- [ ] apply the hook to the whole codebase
