### ISSUE TITLE
use black pre-commit (https://github.com/psf/black) as an autoformatting tool

### ISSUE THREAD

**Issue by ZhukovGreen** [oamg/leapp-repository#565]
# Blocked by #562 (line length)

Under the scope:
- [ ] define what parts of our codebase should be excluded from black formatting
- [ ] setup isort pre-commit hook (https://github.com/psf/black) with the following configuration

in pyproject.toml:
```toml
[tool.black]
line_length={line-length}
target_version=["py27","py36","py38"]
exclude={what-to-exclude}
```

in pre-commit.yml:
```yml
  - repo: "https://github.com/psf/black"
    rev: "19.10b0"
    hooks:
      - id: "black"
        name: "Format code (black)"
        language_version: "python3.8" # not yet sure how to add the rest
        exclude: {what-to-exclude}

  - repo: "https://github.com/asottile/blacken-docs"
    rev: "v1.7.0"
    hooks:
      - id: "blacken-docs"
        name: "Format docs (blacken-docs)"
        language_version: "python3.8"
        args: ["-l", "64"]
        additional_dependencies:
          - "black==19.10b0"
```

- [ ] apply the hook to the whole codebase
